version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo5
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    command: npm start
    restart: always
    volumes:
      - ./dist:/usr/app
    ports:
      - '5050:5050'
    links:
      - mongo
      